name: Build and Deploy dbt Job

on:
  push:
    branches: ["master"]
    paths:
      - "models/**"
      - "seeds/**"
      - "tests/**"
      - "macros/**"
      - "dbt_project.yml"
      - "Dockerfile"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build, tag, and push image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          secrets: |
            aws_region=${{ secrets.AWS_REGION }}
            s3_key=${{ secrets.S3_ACCESS_KEY_ID }}
            s3_secret=${{ secrets.S3_SECRET_ACCESS_KEY }}
            pg_host=${{ secrets.POSTGRES_HOST }}
            pg_port=${{ secrets.POSTGRES_PORT }}
            pg_user=${{ secrets.POSTGRES_USER }}
            pg_password=${{ secrets.POSTGRES_PASSWORD }}
            pg_database=${{ secrets.POSTGRES_DATABASE }}
