name: Build and Deploy dbt Job

on:
  push:
    branches: ["master"]
    paths:
      - "models/**"
      - "seeds/**"
      - "tests/**"
      - "macros/**"
      - "dbt_project.yml"
      - "Dockerfile"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build, tag, and push image to GHCR
        run: |
          IMAGE_TAG=dbt-job

          echo "Building image..."
              docker build \
              --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
              --build-arg S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }} \
              --build-arg S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }} \
              --build-arg POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              --build-arg POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              --build-arg POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }} \
              -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

          echo "Tagging latest..."
          docker tag $REGISTRY/$IMAGE_NAME:$IMAGE_TAG $REGISTRY/$IMAGE_NAME:latest

          echo "Pushing image to GHCR..."
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          docker push $REGISTRY/$IMAGE_NAME:latest

          # Export for later jobs
          echo "image=$REGISTRY/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV
